site_name: ZhangzrJerry
site_description: "Jerry's personal website"

plugins:
  - glightbox
nav:
  - Homepage: index.md
  - Resume: resume.md
  - Projects: 
    - Overview: projects.md
    - Robotics:
      - Yuan Bot: projects/yuan-bot.md
      - Kylin 2022: projects/kylin-2022.md
      - Kylin 2021: projects/kylin-2021.md
      - Kylin 2020: projects/kylin-2020.md
    - Practice: 
      - Intelligent Book Recommendation System: projects/intelligent-book-recommendation-system.md
      - Dual Motor Drive Board: projects/dual-motor-drive-board.md
      - Knowledge Graph Construction: projects/knowledge-graph-construction.md
      - FRC Data Collection Software: projects/frc-data-collection-software.md

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/favicon.ico
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.path
    - navigation.tracking
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.image.lightbox
    - content.card

  language: en
  palette:
    - primary: indigo
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/projects.css

extra_javascript:
  - javascripts/projects.js

markdown_extensions:
  - attr_list
  - md_in_html
  - codehilite:
      guess_lang: false

extra:
    social:
        - icon: fontawesome/regular/envelope
          link: zhangzrjerry@outlook.com
        - icon: fontawesome/brands/github
          link: https://github.com/ZhangzrJerry

