name: Metrics

on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * 1,3,5"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - name: left
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.left.svg

          # Options
          user: ZhangzrJerry
          template: classic
          base: header, activity, community, metadata
          config_timezone: Asia/ShangHai
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_ignored: TeX, CMake, Html
          plugin_languages_threshold: 1%
          plugin_languages_details: lines, percentage
          plugin_languages_indepth: yes
          plugin_languages_aliases: Jupyter Notebook:Python
          commits_authoring: zzhangje, zzhangje@connect.ust.hk
          config_padding: 0, 8 + 11%
          config_order: base.header, base.activity+community, languages

      - name: right
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.right.svg

          # Options
          user: ZhangzrJerry
          template: classic
          base: achievements, stargazers
          config_timezone: Asia/Shanghai
          plugin_achievements: yes
          # plugin_achievements_threshold: C
          plugin_achievements_limit: 6
          plugin_stargazers_map: yes
          plugin_stargazers_map_legend: yes
          plugin_stargazers_map_legend_style: circle
          plugin_stargazers_map_legend_scale: 0.5
          config_padding: 0, 8 + 11%
          config_order: achievements, stargazers
