name: Metrics

on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - name: left
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.left.svg

          # Options
          user: ZhangzrJerry
          template: classic
          base: header, activity, community, metadata
          config_timezone: Asia/ShangHai
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_ignored: TeX, CMake
          plugin_languages_threshold: 2%
          plugin_languages_details: lines, percentage
          plugin_languages_indepth: yes
          plugin_languages_aliases: 'Python:Ipynb'
          commits_authoring: zzhangje, zzhangje@connect.ust.hk
          plugin_steam: yes
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam_achievements_limit: 2
          plugin_steam_games_limit: 1
          plugin_steam_playtime_threshold: 2
          plugin_steam_recent_games_limit: 1
          plugin_steam_sections: player, most-played
          plugin_steam_user: 7656119919898138
          config_padding: 0, 8 + 11%
          config_order: base.header, base.activity+community, languages, steam

      - name: right
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.right.svg

          # Options
          user: ZhangzrJerry
          template: classic
          base: ""
          config_timezone: Asia/Shanghai
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_limit: 6
          plugin_stargazers: yes
          config_padding: 0, 8 + 11%
          config_order: achievements, stargazers